import type { Position } from './types';

export type FormationTemplateSlot = {
  position: Position;
  top: number;  // % desde arriba (0 = arco rival, 100 = arco propio)
  left: number; // % desde la izquierda
};

export type FormationTemplate = {
  id: string;
  name: string;
  slots: FormationTemplateSlot[];
};

export const FORMATION_TEMPLATES: FormationTemplate[] = [
  {
    id: '4-3-3',
    name: '4-3-3',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 52, left: 50 },
      { position: 'MC',  top: 40, left: 30 },
      { position: 'MC',  top: 40, left: 70 },
      { position: 'EXI', top: 18, left: 12 },
      { position: 'DC',  top: 12, left: 50 },
      { position: 'EXD', top: 18, left: 88 },
    ],
  },
  {
    id: '4-3-3-flat',
    name: '4-3-3 (plano)',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MC',  top: 45, left: 25 },
      { position: 'MC',  top: 45, left: 50 },
      { position: 'MC',  top: 45, left: 75 },
      { position: 'EXI', top: 18, left: 12 },
      { position: 'DC',  top: 12, left: 50 },
      { position: 'EXD', top: 18, left: 88 },
    ],
  },
  {
    id: '4-2-3-1',
    name: '4-2-3-1',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 57, left: 38 },
      { position: 'MCD', top: 57, left: 62 },
      { position: 'EXI', top: 30, left: 12 },
      { position: 'MO',  top: 30, left: 50 },
      { position: 'EXD', top: 30, left: 88 },
      { position: 'DC',  top: 12, left: 50 },
    ],
  },
  {
    id: '4-4-2-flat',
    name: '4-4-2 (plano)',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MDI', top: 45, left: 15 },
      { position: 'MC',  top: 45, left: 38 },
      { position: 'MC',  top: 45, left: 62 },
      { position: 'MDD', top: 45, left: 85 },
      { position: 'DC',  top: 15, left: 35 },
      { position: 'DC',  top: 15, left: 65 },
    ],
  },
  {
    id: '4-4-2-diamond',
    name: '4-4-2 (diamante)',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 57, left: 50 },
      { position: 'MC',  top: 42, left: 25 },
      { position: 'MC',  top: 42, left: 75 },
      { position: 'MO',  top: 27, left: 50 },
      { position: 'DC',  top: 12, left: 35 },
      { position: 'DC',  top: 12, left: 65 },
    ],
  },
  {
    id: '4-3-2-1',
    name: '4-3-2-1 (árbol)',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 55, left: 50 },
      { position: 'MC',  top: 42, left: 28 },
      { position: 'MC',  top: 42, left: 72 },
      { position: 'SD',  top: 25, left: 35 },
      { position: 'SD',  top: 25, left: 65 },
      { position: 'DC',  top: 10, left: 50 },
    ],
  },
  {
    id: '4-2-2-2',
    name: '4-2-2-2',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 55, left: 35 },
      { position: 'MCD', top: 55, left: 65 },
      { position: 'EXI', top: 33, left: 15 },
      { position: 'EXD', top: 33, left: 85 },
      { position: 'DC',  top: 12, left: 35 },
      { position: 'DC',  top: 12, left: 65 },
    ],
  },
  {
    id: '4-5-1',
    name: '4-5-1',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MDI', top: 48, left: 15 },
      { position: 'MC',  top: 48, left: 35 },
      { position: 'MCD', top: 55, left: 50 },
      { position: 'MC',  top: 48, left: 65 },
      { position: 'MDD', top: 48, left: 85 },
      { position: 'DC',  top: 12, left: 50 },
    ],
  },
  {
    id: '3-5-2',
    name: '3-5-2',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'DFC', top: 72, left: 25 },
      { position: 'DFC', top: 72, left: 50 },
      { position: 'DFC', top: 72, left: 75 },
      { position: 'LI',  top: 55, left: 10 },
      { position: 'MCD', top: 48, left: 50 },
      { position: 'MC',  top: 38, left: 30 },
      { position: 'MC',  top: 38, left: 70 },
      { position: 'LD',  top: 55, left: 90 },
      { position: 'DC',  top: 12, left: 35 },
      { position: 'DC',  top: 12, left: 65 },
    ],
  },
  {
    id: '3-4-3',
    name: '3-4-3',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'DFC', top: 72, left: 25 },
      { position: 'DFC', top: 72, left: 50 },
      { position: 'DFC', top: 72, left: 75 },
      { position: 'MDI', top: 48, left: 12 },
      { position: 'MC',  top: 42, left: 35 },
      { position: 'MC',  top: 42, left: 65 },
      { position: 'MDD', top: 48, left: 88 },
      { position: 'EXI', top: 18, left: 12 },
      { position: 'DC',  top: 10, left: 50 },
      { position: 'EXD', top: 18, left: 88 },
    ],
  },
  {
    id: '5-3-2',
    name: '5-3-2',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 10 },
      { position: 'DFC', top: 72, left: 28 },
      { position: 'DFC', top: 72, left: 50 },
      { position: 'DFC', top: 72, left: 72 },
      { position: 'LD',  top: 72, left: 90 },
      { position: 'MC',  top: 45, left: 25 },
      { position: 'MC',  top: 45, left: 50 },
      { position: 'MC',  top: 45, left: 75 },
      { position: 'DC',  top: 12, left: 35 },
      { position: 'DC',  top: 12, left: 65 },
    ],
  },
  {
    id: '4-1-4-1',
    name: '4-1-4-1',
    slots: [
      { position: 'PT',  top: 88, left: 50 },
      { position: 'LI',  top: 72, left: 12 },
      { position: 'DFC', top: 72, left: 33 },
      { position: 'DFC', top: 72, left: 67 },
      { position: 'LD',  top: 72, left: 88 },
      { position: 'MCD', top: 57, left: 50 },
      { position: 'MDI', top: 42, left: 12 },
      { position: 'MC',  top: 42, left: 35 },
      { position: 'MC',  top: 42, left: 65 },
      { position: 'MDD', top: 42, left: 88 },
      { position: 'DC',  top: 12, left: 50 },
    ],
  },
];
